name: DEV - Build and Test

on:
  push:
    branches-ignore: [trunk]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEBUG: ${{ secrets.DEBUG_VALUE }}
      POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD }}
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install project
        run: |
          pip install -e .

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt
      - name: Install project
        run: |
          pip install -e .
      - name: Run tests and generate coverage report
        run: pytest --cov=./ --cov-report=xml
